### ISSUE TITLE
Replace Kafka with NATs

### ISSUE THREAD

**Issue by ilumin** [japahubs/japahubs-backend#15]
Kafka might not be suitable for Japahub in initial state.

**Comment by prosper20** [comment]
Done and made a pull request. Test it out and let me know how it goes so that I can merge it. you need to have the file .env.development dm for the env variables

**Comment by ilumin** [comment]
From this #16 you have to run 

```sh
docker volume create nats1
docker volume create nats2
docker volume create nats3
```

Then run `docker compose up -d`
